name: deploy-dev

on:
  pull_request:
    types:
      - closed
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      TEST: 'Hello World'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Rsync to Server
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          remote_path: /home/ubuntu/app
          remote_host: dev-server.dzamanillo.com
          remote_user: ubuntu
          remote_key: ${{ secrets.DEV_DEPLOY_KEY }}

      - name: Restart or Start PM2 Process
        uses: appleboy/ssh-action@master
        with:
          host: dev-server.dzamanillo.com
          username: ubuntu
          key: ${{ secrets.DEV_DEPLOY_KEY }}
          script: |
            cd /home/ubuntu
            if [ ! -d "app" ]; then
              mkdir app
            fi
            cd /home/ubuntu/app
            pwd
            pm2 restart --interpreter ./node_modules/.bin/ts-node src/main.ts || pm2 start --interpreter ./node_modules/.bin/ts-node src/main.ts
            sudo systemctl restart nginx
          envs: TEST
